### ISSUE TITLE
v1.3.0?

### ISSUE THREAD

**Issue by OliverEvans96** [gleam-lang/vscode-gleam#13]
Hello!

Just noticed that the [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=Gleam.gleam&ssr=false#overview) says that the latest version is v1.3.0, but I only see v1.2.0 here. Which is correct?

Thanks,
Oliver

**Comment by lpil** [comment]
Oh dear! What has happened here? I shall investigate.

**Comment by lpil** [comment]
All fixed, thank you for the report
