### ISSUE TITLE
discarded args not greyed out

### ISSUE THREAD

**Issue by inoas** [gleam-lang/vscode-gleam#24]
github:

<img width="514" alt="Screen Shot 2022-06-27 at 14 32 19" src="https://user-images.githubusercontent.com/20972207/175944129-f16e6c14-e63a-4964-9f18-e6b3c5556457.png">

vscode (Dark+ (default dark):

<img width="443" alt="Screen Shot 2022-06-27 at 14 34 20" src="https://user-images.githubusercontent.com/20972207/175944166-30b0afd8-761e-401f-9915-373aaa09265a.png">

**Comment by lpil** [comment]
Sounds like a good thing to add 👍
