### ISSUE TITLE
Make the gleam executable file/path configurable.

### ISSUE THREAD

**Issue by schurhammer** [gleam-lang/vscode-gleam#26]
Due to how my environment is set up, the gleam executable is not in $PATH when the gleam extension is loaded, and thus it can not start the language server.
(Path is set in .bashrc which is apparently not loaded)

I think the simplest and/or most general solution would be to add a setting where you can manually specify the path to the gleam executable.

**Comment by lpil** [comment]
Sounds like a great idea!
