### ISSUE TITLE
disable or config formatting patterns

### ISSUE THREAD

**Issue by mateus-md** [gleam-lang/vscode-gleam#28]
hello,
i recently installed this extension along with the gleam language itself. I would like to know how to disable the default formatting command on save, or at least, configure it to use 4 spaces as indentation and do not put a empty newline on the end of the file.
the command ``npm run compile-watch`` returns the fallowing error:
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path [...]/gleam/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '[...]/gleam/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mmd/.npm/_logs/2022-09-08T21_27_12_314Z-debug-0.log
```
any help would be great

**Comment by lpil** [comment]
Hello!

Gleam uses 2 space indentation, and according to UNIX it is invalid to have a text file without a trailing newline.

Automatic formatting is a vscode feature and you can enable or disable it in your user settings like so:

https://github.com/gleam-lang/vscode-gleam/blob/19a4a82f1afc769dfa32bbc9be22215249a8d1c2/package.json#L48-L50
