### ISSUE TITLE
Support the `use` keyword

### ISSUE THREAD

**Issue by hfjallemark** [gleam-lang/vscode-gleam#34]
I'm getting the following error when trying out the new `use` syntax in VSCode:

```
Syntax error

This operator has no value on its right side.

Hint: Remove it or put a value after it.
```

I'm running `v2.0.0` of the extension.

**Comment by lpil** [comment]
Hello! This error is caused by having an older version of Gleam installed that does not support `use`. If you upgrade to v0.25.0 and restart your editor that'll resolve the issue. Cheers
