### ISSUE TITLE
Unused recursive function not highlighted as being unused.

### ISSUE THREAD

**Issue by macroby** [gleam-lang/vscode-gleam#51]
![vscode_gleam_ext_error](https://github.com/gleam-lang/vscode-gleam/assets/95256045/cfc1cf03-970b-449f-b095-fe7919d16e3d)
unused_non_recursive_func() is highlighted by vs code since it is unused, but unused_recursive_func(flag: Bool) is not highlighted since it is used within itself, which convinces vscode that it is being used. I think this is wrong and that unused_recursive_func(flag: Bool) should be marked as unused.

\
The same situation but in rust and using the rust-analyzer extension:
![rust_unused_rec_func](https://github.com/gleam-lang/vscode-gleam/assets/95256045/f053604b-ba76-43ee-b5d1-7859b2bed7ff)

**Comment by lpil** [comment]
Aye, this is a known issue with the dead code detection. This feature is due a full rewrite and will cover this case when that happens. Thank you, and sorry for the annoyance of this problem.
