### ISSUE TITLE
Poor LSP or misconfiguration?

### ISSUE THREAD

**Issue by pettomartino** [gleam-lang/vscode-gleam#58]
Hi,

First of all, Gleam is AWESOME and I'm super keen to play with it.

But..
I've installed Gleam following the documentation.
<img width="711" alt="image" src="https://github.com/gleam-lang/vscode-gleam/assets/101433/d1f09b04-bc27-4575-8e21-ed7d29057c06">
<img width="436" alt="image" src="https://github.com/gleam-lang/vscode-gleam/assets/101433/bf9c8a6d-0890-46f2-af0f-ff7893dc7ba5">

But the LSP doesn't seen to be helping much.

I got code sample from the repo and I was trying to explore the LSP but no luck.
<img width="691" alt="image" src="https://github.com/gleam-lang/vscode-gleam/assets/101433/35447cf0-3086-405f-aa47-52d54044f1a2">
<img width="631" alt="image" src="https://github.com/gleam-lang/vscode-gleam/assets/101433/496d429d-42f8-4dc6-84ea-cc416382dcae">

I wonder if I'm still missing something, or this is what I should expect from the current LSP?

**Comment by lpil** [comment]
Hello! The language server is new and the current focus of Gleam development, more to come soon.
