### ISSUE TITLE
Publish on open-vsx

### ISSUE THREAD

**Issue by glennsl** [gleam-lang/vscode-gleam#6]
Eclipse's [Open VSX Registry](http://open-vsx.org/) was created as an alternative to the Visual Studio Marketplace because the latters [Terms of Use](https://cdn.vsassets.io/v/M146_20190123.39/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf) allow only "Visual Studio Products" access.

Publishing on http://open-vsx.org/ as well would therefore make this available to, amongst others, [VSCodium](https://vscodium.com/), [Onivim](https://www.onivim.io/) and [Theia](https://theia-ide.org/).

See their documentation for [how to publish](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by WhoAteDaCake** [comment]
+1 This would be very useful :)

**Comment by lpil** [comment]
Done! Wow open VSX is sooooo much easier to use than the official registry
