### ISSUE TITLE
Language Server: Couldn't create connection to server

### ISSUE THREAD

**Issue by PhilippMolitor** [gleam-lang/vscode-gleam#61]
The language server does not work for my installation. Gleam 1.0 was installed via `asdf`, as described in the gleam docs.

Gleam Language Server VSCode output:
```
[Error - 11:04:37 AM] Gleam Language Server client: couldn't create connection to server.
Launching server using command gleam failed. Error: spawn gleam ENOENT
```

**Comment by lpil** [comment]
Hello! You need to ensure that your editor has the asdf directory in its PATH for it to be able to find the `gleam` program.

**Comment by PhilippMolitor** [comment]
Thank you. I tinkered around with the installation a bit, seems like asdf does indeed get loaded correctly without modifications when rebooting the whole system after install.
