### ISSUE TITLE
`@external` autocomplete duplicates the `@` sign

### ISSUE THREAD

**Issue by trag1c** [gleam-lang/vscode-gleam#73]
Version: v2.7.0

Autocompleting
<img width="586" alt="45921" src="https://github.com/gleam-lang/vscode-gleam/assets/77130613/befd9b06-6d2f-489a-a4e1-2ca3628c4b38">
produces
<img width="310" alt="30146" src="https://github.com/gleam-lang/vscode-gleam/assets/77130613/8ef19bbc-1ec7-48b6-8a4a-29564784fb25">

I didn't find any prior issues; I'm also not sure if this is a `vscode-gleam`-specific thing or if this should be in https://github.com/gleam-lang/gleam, so sorry in advance.

**Comment by lpil** [comment]
Hello! Yes this is from the snippets in this repo
