### ISSUE TITLE
lsp autocomplete module namespace and duplication

### ISSUE THREAD

**Issue by jshawl** [gleam-lang/vscode-gleam#80]
I am a happy vscode gleam user! I wanted to report two small autocomplete issues:

1. typing `.` shows all the methods for imported modules (not just those in the `list` module) (I think this one is for https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/language_server) 
2. clicking on an autocomplete suggestion adds the entire suggestion to the editor (instead of just the completion part) e.g. output should be `list.map` not `list.list.map`

![gleam-lsp](https://github.com/gleam-lang/vscode-gleam/assets/3824954/1bc16875-07bb-4b86-808e-48086003766e)

Thank you!

**Comment by lpil** [comment]
Hello! There already exists issues for these. Thanks

**Comment by Zhomart** [comment]
I don't see it in the issue list. Can you please share where you're trackign it?

![image](https://github.com/gleam-lang/vscode-gleam/assets/830536/be281df6-3f7e-457b-8afc-929426c6e641)

**Comment by Zhomart** [comment]
Seems like this one https://github.com/gleam-lang/gleam/issues/2165
