### ISSUE TITLE
Better hover support for each variable type

### ISSUE THREAD

**Issue by tarikyildizci** [gleam-lang/vscode-gleam#87]
Coming from typescript, in case of an error my workflow is usually like this:
- hover over the wiggly
- try to understand the error message
- check the type of the variable (fn, method etc.) I am hovering on
- check other types by hovering on them

what happens with gleam is:
- if no errors, hover over anything to see its type
- if errors, I can only see the error message, and if the whole line is wiggly, I cannot see why the error happened because I cannot find out what the function expects, what my variable type is etc.

I am also including an example image. Even if I hover over response, httpc, send, or request, I get the same text. I believe it would be helpful to see the hovered item's type below as well. 

<img width="379" alt="image" src="https://github.com/user-attachments/assets/0a7ebe97-ecd0-4593-8ef8-ff092148a2aa">

**Comment by tarikyildizci** [comment]
I am pretty new to Gleam, so this might not be an issue at all, but I have also noticed that when this behavior happens it usually highlights multiple lines, and it happens in the return statement of a function

**Comment by lpil** [comment]
Sorry, I'm not understanding. Why can't you hover in Gleam?

**Comment by tarikyildizci** [comment]
I can hover, but I cannot see the details I need sometimes. Let me explain with a function:
```
pub fn fetch(url: String) {
  use uri <- result.try(uri.parse(url))
  use req <- result.try(request.from_uri(uri))

  let resp_result = httpc.send(req)

  use resp <- result.try(resp_result)
  Ok(Nil)
}
```

Compiler gives an error as the return type of this function is faulty (I I have no idea what I am doing in here :P, but that is an issue with me and the error is irrelevant for this issue). 

When I try to hover over `.send` to see what it accepts and returns, I can only see `Result(a, Nil)`. In typescript, when there is an error and I hover over a method that has the wiggly lines It shows me error on top, and then the type annotations of the method below. 

I think it would be helpful to show types and errors at the same time. I hope I made things more clear.

**Comment by tarikyildizci** [comment]
Here is an example in typescript:
<img width="607" alt="image" src="https://github.com/user-attachments/assets/6e5a5103-0c2e-4784-845c-990ef08e8cbe">
Although there is an error, it still tells me that Response.ok is a boolean at the end, which I couldn't see when using gleam.

**Comment by tarikyildizci** [comment]
Okay, thanks for the clarification.
