### ISSUE TITLE
[Feature Request] Add a type explorer like what the "TypeScript Explorer" extension offers

### ISSUE THREAD

**Issue by Olian04** [gleam-lang/vscode-gleam#89]
I'd like for the extension to include a type explorer similar to what the ["TypeScript Explorer" extension](https://marketplace.visualstudio.com/items?itemName=mxsdev.typescript-explorer) offers.

From the "TypeScript Explorer" extension:
![image](https://github.com/user-attachments/assets/34c64cad-d694-4e65-9232-8ac3c2808082)
![gif](https://user-images.githubusercontent.com/16108792/200933940-b735a2a3-cc9d-40de-a4a9-c10c080eead8.gif)

While Typescript and Gleam are very different, I think that a type explorer that shows the types of all modules in the current workspace, both local and dependencies, would be very useful.

**Comment by Olian04** [comment]
@lpil I don't know.

**Comment by lpil** [comment]
OK thank you. Please feel free to reopen when you have more information.
